project:
  type: website
  output-dir: docs

website:
  title: "Collin Henkel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: about.qmd
        text: About
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/collin-henkel-55aa2533a/

format:
  html:
    theme: zephyr
    css: styles.css

editor: visual
